from pages.ct.fun import table
ioes = [
    'Alumínio: AL³⁺',
    'Amónio: NH₄⁺',         
    'Bário: Ba²⁺',
    'Berílio: Be²⁺',
    'Bismuto: Bi³⁺',
    'Boro: B³⁺', 
    'Cálcio: Ca²⁺',
    'Césio: Cs⁺',
    'Chumbo: Pb²⁺',
    'Cobre(I): Cu⁺',
    'Cobre(II): Cu²⁺',
    'Ferro (II): Fe²⁺',
    'Ferro (III): Fe³⁺',
    'Hidrogénio: H⁺',
    'Lítio: Li⁺',
    'Magnésio: Mg²⁺',
    'Manganésio (II): Mn²⁺',
    'Manganésio (III): Mn³⁺',
    'Mercúrio (I): Hg₂²⁺',
    'Mercúrio (II): Hg²⁺',
    'Ouro (I): Au⁺',
    'Ouro (III): Au³⁺',
    'Oxónio: H₃O⁺',
    'Potássio: K⁺',
    'Prata: Ag⁺',
    'Sódio: Na⁺',
    'Zinco: Zn²⁺',
    'Acetato: CH₃CO₂⁻',
    'Aluminato: AlO₂⁻',
    'Borato: BO₃³⁻',
    'Bromato: BrO₃⁻',
    'Brometo: Br⁻',
    'Bromito: BrO₂⁻',
    'Carbonato: CO₃²⁻',
    'Cianato: CNO⁻',
    'Cianeto: CN⁻',
    'Clorato: ClO₃⁻',
    'Cloreto: Cl⁻',
    'Clorito: ClO₂⁻',
    'Cromato: CrO₄²⁻',
    'Dicromato: Cr₂O₇²⁻',
    'Fluoreto: F⁻',
    'Fosfato: PO₄³⁻',
    'Fosfeto: P³⁻',
    'Fosfito: PO₃³⁻',
    'Hidreto: H⁻',
    'Hidrogenocarbonato: HCO₃⁻',
    'Hidrogenodifluoreto: HF₂⁻',
    'Hidrogenofosfato: HPO₄²⁻',
    'Hidrogenossulfato: HSO₄⁻',
    'Hidrogenossulfito: HSO₃⁻',
    'Hidrogenossulfureto: HS⁻',
    'Hidroperóxido: HO₂⁻',
    'Hidróxido: HO⁻',
    'Hipobromito: BrO⁻',
    'Hipoclorito: ClO⁻',
    'Hipofosfito: H₂PO₂⁻',
    'Hipoiodito: IO⁻',
    'Iodato: IO₃⁻',
    'Iodeto: I⁻',
    'Manganato: MnO₄²⁻',
    'Nitrato: NO₃⁻',
    'Nitrito: NO₂⁻',
    'Oxalato: C₂O₄²⁻',
    'Óxido: O²⁻',
    'Permanganato: MnO₄⁻',
    'Peróxido: O₂²⁻',
    'Persulfato: S₂O₈²⁻',
    'Sulfato: SO₄²⁻',
    'Sulfito: SO₃²⁻',
    'Sulfureto: S²⁻',
    'Tiocianato: SCN⁻',
    'Tiossulfato: S₂O₃²⁻',
    'Tiossulfito: S₂O₂²⁻',
    'Triiodeto: I₃⁻',
    'Zincato: ZnO₂²⁻',
]

def ions_table():
    table(ioes)