from pages.ct.fun import table

red = ['2F⁻ (aq)',
       '2SO₄²⁻(aq)',
       'Co²⁺ (aq)',
       'Ce³⁺ (aq)',
       'Au (s)',
       '2Cl⁻ (aq)',
       '2Br⁻ (aq)',
       '2OH⁻ (aq)',
       '2Hg (l)',
       'Ag (s)',
       'Fe²⁺ (aq)',
       '2I⁻ (aq)',
       'Cu (s)',
       'Sn²+ (aq)',
       'H₂ (g)',
       'Pb (s)',
       'Sn (s)',
       'Ni (s)',
       'Co (s)',
       'Cd (s)',
       'Fe (s)',
       'Cr (s)',
       'Zn (s)',
       'Mn (s)',
       'Al (s)',
       'Be (s)',
       '2H- (g)',
       'Mg (s)',
       'Na (s)',
       'Ca (s)',
       'Sr (s)',
       'Ba (s)',
       'K (s)',
       'Li (s)']

def red_table():
    table(red)